### PR TITLE
BD-908:Relicense ThunderUI to Metrological Apache 

### PR DESCRIPTION
**Pull request by mallikarjuna54**
Reason for change:Relicense ThunderUI to Metrological Apache
Test Procedure: Jenkin build should pass after License header changes for RDK for listed repos
BD-908:Relicense ThunderUI to Metrological Apache
Risks: None

### CODE REVIEW

**Review by mhughesacn — CHANGES_REQUESTED** [review]
Hi Mallikarjuna: Two files still with RDK headers:
CMakeLists.txt
src/js/plugins/persistentStore.js
Thanks.

**Comment by mhughesacn** [comment]
Thanks Mallikarjuna. I have completed the Id work and I am happy for this to merge.

**Comment by pradeeptakdas** [comment]
Hi @woutermeek 
Please merge this PR if you are Happy. Thanks!

**Comment by mhughesacn** [comment]
Closed in favour of https://github.com/rdkcentral/ThunderUI/pull/48 with the same changes.

**Pull request closed without merging**
