### PR TITLE
Integrating BluetoothManager, HDMI Input, RDK Shell, Warehouse, WifiManger plugin to Thunder UI

### PR DESCRIPTION
**Pull request by Nivedha340**

### CODE REVIEW

**Comment by woutermeek** [comment]
@Nivedha340 it is a little confusing that we now have 2 bluetooth plugins and 2 wifi plugins. I think it might be good to put RDKServices related plugins in a subfolder and the same for ThunderNanoServices plugins.

**Comment by Nivedha340** [comment]
> @Nivedha340 it is a little confusing that we now have 2 bluetooth plugins and 2 wifi plugins. I think it might be good to put RDKServices related plugins in a subfolder and the same for ThunderNanoServices plugins.

Does it mean to move bluetoothManager.js and wifiManager.js files to a separate folder named 'rdkservices' inside the 'plugins' folder and keep all remaining files as it is?
So the final path of Bluetooth and wifi rdkservice plugins will be 'ThunderUI/tree/master/src/js/plugins/rdkservices/bluetoothManager.js' and 'ThunderUI/tree/master/src/js/plugins/rdkservices/wifiManager.js'
Could you please confirm?

**Comment by woutermeek** [comment]
Yes please, that would be great

**Comment by Nivedha340** [comment]
> Yes please, that would be great

Ok, @woutermeek .Changes are made. Could you please review and merge the PR?

**Review by woutermeek — APPROVED** [review]

**Pull request merged**
